
Select, filter, arrange, mutate

```{r}
setwd("C:/Users/Propietario/Desktop/ToolBox")
counties <- readRDS('counties.rds')
counties
```
```{r}
counties %>%
  # Select the five columns 
  select(state, county, population, men, women) %>%
  # Add the proportion_men variable
  mutate(proportion_men= men/population*100) %>%
  # Filter for population of at least 10,000
  filter(population >10000) %>%
  # Arrange proportion of men in descending order 
  arrange(desc(proportion_men))
```
Summarize, group_by, 

```{r}
counties %>%
  # Summarize to find minimum population, maximum unemployment, and average income
  summarize(min_population = min(population),
            max_unemployment = max(unemployment),
            average_income = mean(income))
```

```{r}
counties %>%
  group_by(state) %>%
  summarize(total_area = sum(land_area),
            total_population = sum(population)) %>%
  # Add a density column
  mutate(density = total_population / total_area) %>%
  # Sort by density in descending order
  arrange(desc(density))
```

```{r}
counties %>%
  # Group and summarize to find the total population
  group_by(region, state) %>%
  summarize(total_pop = sum(population)) %>%
  # Calculate the average_pop and median_pop columns 
  summarize(average_pop=mean(total_pop),
            median_pop=median(total_pop))
```

```{r}
counties %>%
  # Group by region
  group_by(region) %>%
  # Find the greatest number of citizens who walk to work
  top_n(1, walk)
```

```{r}
counties %>%
  # Find the total population for each combination of state and metro
  group_by(state, metro) %>%
  summarize(total_pop = sum(population)) %>%
  # Extract the most populated row for each state
  top_n(1, total_pop) %>%
  # Count the states with more people in Metro or Nonmetro areas
  ungroup(metro) %>%
  count(metro)
```

Selecting

```{r}
glimpse(counties)

counties %>%
  # Select state, county, population, and industry-related columns
  select(state, county, population, professional:production) %>%
  # Arrange service in descending order 
  arrange(desc(service))
```
```{r}
counties %>%
  # Select the state, county, population, and those ending with "work"
  select(state, county, population, ends_with('work')) %>%
  # Filter for counties that have at least 50% of people engaged in public work
  filter(public_work > 50)
```
Rename 

```{r}
counties %>%
  # Count the number of counties in each state
  count(state) %>%
  # Rename the n column to num_counties
  rename(num_counties=n)
```

```{r}
counties %>%
  # Select state, county, and poverty as poverty_rate
  select(state, county, poverty_rate=poverty)
```

Transmute

```{r}
counties %>%
  # Keep the state, county, and populations columns, and add a density column
  transmute(state, county, population, density=population/land_area) %>%
  # Filter for counties with a population greater than one million 
  filter(population > 1000000) %>%
  # Sort density in ascending order 
  arrange(density)
```

Baby names study case

```{r}
babynames <- readRDS('babynames.rds')

babynames %>%
  # Filter for the year 1990
  filter(year=='1990') %>% 
  # Sort the number column in descending order 
  arrange(desc(number))
```

```{r}
babynames %>%
  # Find the most common name in each year
  group_by(year) %>%
  top_n(1, number)
```

```{r}
library(ggplot2)

selected_names <- babynames %>%
  # Filter for the names Steven, Thomas, and Matthew 
  filter(name %in% c("Steven", "Thomas", "Matthew"))

# Plot the names using a different color for each name
ggplot(selected_names, aes(x = year, y = number, color = name)) +
  geom_line()
```

```{r}
# Calculate the fraction of people born each year with the same name
babynames %>%
  group_by(year) %>%
  mutate(year_total = sum(number)) %>%
  ungroup() %>%
  mutate(fraction = number / year_total) %>%
  # Find the year each name is most common
  group_by(name) %>%
  top_n(1, fraction)
```

```{r}
babynames %>%
  # Add columns name_total and name_max for each name
  group_by(name) %>%
  mutate(name_total = sum(number),
         name_max = max(number)) %>%
  # Ungroup the table 
  ungroup() %>%
  # Add the fraction_max column containing the number by the name maximum 
  mutate(fraction_max=number/name_max)
```

```{r}
babynames_fraction <- babynames %>% 
      group_by(year) %>% 
      mutate(year_total=sum(number),
             fraction=number/year_total)
  
babynames_fraction %>%
  # Arrange the data in order of name, then year 
  arrange(name, year) %>%
  # Group the data by name
  group_by(name) %>%
  # Add a ratio column that contains the ratio of fraction between each year 
  mutate(ratio = fraction / lag(fraction))
```
```{r}
babynames_ratios_filtered <- babynames_fraction %>%
                     arrange(name, year) %>%
                     group_by(name) %>%
                     mutate(ratio = fraction / lag(fraction)) %>%
                     filter(fraction >= 0.00001)

babynames_ratios_filtered %>%
  top_n(1, ratio) %>%
  # Sort the ratio column in descending order 
  arrange(desc(ratio)) %>%
  # Filter for fractions greater than or equal to 0.001
  filter(fraction >= 0.001)
```

